import {useRef,useState} from 'react';
import {useAuth} from '../../context/AuthContext';
type FileSelection={selectionId:string;name:string;size:number};
type Bridge={chooseFolder():Promise<{ok:boolean;data?:{cancelled?:boolean;files:FileSelection[];skipped:number};error?:{message:string}}>;
 chooseRepository():ReturnType<Bridge['chooseFolder']>;
 uploadEvidence(projectId:string,selectionId:string):Promise<{ok:boolean;error?:{message:string}}>};
export default function DesktopSources(){
 const {activeProject}=useAuth();const [files,setFiles]=useState<FileSelection[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const stop=useRef(false),running=useRef(false);const bridge=window.orchestra as unknown as Bridge;
 async function choose(repository=false){if(running.current)return;running.current=true;setBusy(true);setError('');try{const result=await (repository?bridge.chooseRepository():bridge.chooseFolder());if(!result.ok)throw new Error(result.error?.message??'Folder selection failed');if(result.data?.cancelled)return;setFiles(result.data?.files??[]);setMessage(`${result.data?.files.length??0} documents selected; ${result.data?.skipped??0} hidden, unsupported or excluded entries skipped. Nothing imported yet.`);}catch(e){setError(e instanceof Error?e.message:'Folder selection failed');}finally{running.current=false;setBusy(false);}}
 async function importFiles(){if(running.current||!activeProject)return;running.current=true;stop.current=false;setBusy(true);setError('');const projectId=activeProject.id;let saved=0;try{for(const file of files){if(stop.current)break;setMessage(`Importing ${saved+1} of ${files.length}: ${file.name}`);const result=await bridge.uploadEvidence(projectId,file.selectionId);if(!result.ok)throw new Error(`${file.name}: ${result.error?.message??'Import failed'}`);saved++;setFiles(current=>current.filter(item=>item.selectionId!==file.selectionId));}setMessage(`${saved} documents saved to Memory${stop.current?'; remaining imports stopped':''}. Processing continues in the local worker.`);}catch(e){setError(`${saved} documents saved. ${e instanceof Error?e.message:'Import failed'}. Check Memory before selecting the remaining files again.`);}finally{running.current=false;setBusy(false);}}
 return <section className="rounded-xl border border-[var(--border-soft)] bg-[var(--bg-card)] p-5" aria-labelledby="desktop-sources-heading">
  <h2 id="desktop-sources-heading" className="text-sm font-semibold text-[var(--text-default)]">Local project documents</h2>
  <p className="mt-2 text-xs text-[var(--text-muted)]">Choose a folder, including a repository’s documentation folder. Only PDF, Word, text, Markdown and spreadsheet documents are included. Hidden files, symbolic links, dependencies and build outputs are excluded. No continuous monitoring or automatic home-folder indexing. Configured AI may receive imported evidence.</p>
  <p className="mt-2 text-xs text-[var(--text-muted)]">Repository selection also previews supported UTF-8 source code as text evidence. This is a working-tree snapshot, not commit history or approved requirements. Review the file list before importing.</p>
  <button disabled={busy||!activeProject} onClick={()=>void choose(true)} className="mt-3 rounded-lg border border-[var(--border-soft)] px-3 py-2 text-xs text-[var(--text-default)]">Choose Git repository</button>
  <div className="mt-3 flex gap-3"><button disabled={busy||!activeProject} onClick={()=>void choose()} className="rounded-lg bg-[var(--terracotta)] px-3 py-2 text-xs text-white disabled:opacity-50">Choose document folder</button>{files.length>0&&<button disabled={busy} onClick={()=>void importFiles()} className="rounded-lg border border-[var(--border-soft)] px-3 py-2 text-xs text-[var(--text-default)]">Import {files.length} documents</button>}{busy&&<button onClick={()=>{stop.current=true;}} className="text-xs text-[var(--text-default)]">Stop after current file</button>}</div>
  {files.length>0&&<ul aria-label="Selected documents" className="mt-3 max-h-40 overflow-auto text-xs text-[var(--text-muted)]">{files.map(file=><li key={file.selectionId}>{file.name}</li>)}</ul>}
  {message&&<p role="status" className="mt-3 text-xs text-[var(--text-muted)]">{message}</p>}{error&&<p role="alert" className="mt-3 text-xs text-[var(--text-default)]">{error}</p>}
 </section>;
}
