import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,it,expect,vi} from 'vitest';
import DesktopSharedSettings from './DesktopSharedSettings';
import {SharedServerBanner} from '../shell/SharedServerBanner';
import {isDesktop,isSharedDesktop} from '../../lib/desktop';
const connection={id:'11111111-1111-4111-8111-111111111111',serverId:'22222222-2222-4222-8222-222222222222',name:'Synthetic team',origin:'https://team.invalid'};
afterEach(()=>{delete window.orchestra;delete window.orchestraShared;});
function setup(){const bridge={list:vi.fn().mockResolvedValue({ok:true,data:[connection]}),connect:vi.fn().mockResolvedValue({ok:true,data:{connected:true}}),open:vi.fn().mockResolvedValue({ok:true,data:{opened:true}}),remove:vi.fn().mockResolvedValue({ok:false,error:{message:'Server unavailable. Sign-out not confirmed.'}})};Object.assign(window,{orchestra:{shared:bridge}});return bridge;}
it('loads saved descriptors without auto-connecting and requires an explicit connect action',async()=>{const bridge=setup();render(<DesktopSharedSettings/>);await screen.findByRole('button',{name:'Open Synthetic team'});expect(bridge.connect).not.toHaveBeenCalled();expect(bridge.open).not.toHaveBeenCalled();await userEvent.type(screen.getByLabelText('Server name'),'Another server');await userEvent.type(screen.getByLabelText('Server HTTPS address'),'https://another.invalid');await userEvent.click(screen.getByRole('button',{name:'Connect team server'}));expect(bridge.connect).toHaveBeenCalledWith({name:'Another server',origin:'https://another.invalid'});});
it('preserves a server row when sign-out or removal is not confirmed',async()=>{const bridge=setup();render(<DesktopSharedSettings/>);await userEvent.click(await screen.findByRole('button',{name:'Sign out and remove'}));expect(bridge.remove).toHaveBeenCalledWith(connection.id);expect(await screen.findByRole('alert')).toHaveTextContent('Sign-out not confirmed');expect(screen.getByRole('button',{name:'Open Synthetic team'})).toBeInTheDocument();});
it('separates shared identity from local-owner mode and identifies the authoritative origin',async()=>{const close=vi.fn();window.orchestraShared={connection,close,copyText:vi.fn()};expect(isSharedDesktop()).toBe(true);expect(isDesktop()).toBe(false);render(<SharedServerBanner/>);expect(screen.getByRole('complementary',{name:'Connected team server'})).toHaveTextContent(connection.origin);await userEvent.click(screen.getByRole('button',{name:'Return to local'}));expect(close).toHaveBeenCalledOnce();});
