import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import DesktopAiSettings from './DesktopAiSettings';
beforeEach(()=>{window.orchestra={status:vi.fn(),bootstrap:vi.fn(),completeOnboarding:vi.fn(),ai:{inspect:vi.fn().mockResolvedValue({ok:true,data:{configured:false,preferences:null}}),configure:vi.fn().mockResolvedValue({ok:true,data:{cancelled:true}}),revoke:vi.fn().mockResolvedValue({ok:true})}};});
afterEach(()=>{delete window.orchestra;});
it('loads settings and passes only preferences to native key import',async()=>{render(<DesktopAiSettings/>);expect(await screen.findByText('Offline evidence search is available. No AI key is saved.')).toBeInTheDocument();expect(document.querySelector('input[type=password]')).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Import key, test and restart'}));expect(window.orchestra!.ai!.configure).toHaveBeenCalledWith({generationModel:'gpt-5.4-mini',embeddingModel:'text-embedding-3-small',embeddingDimensions:1536,maxRequestsPerDay:50,maxOutputTokens:2048});expect(screen.queryByText('OpenAI key saved on this Mac.')).not.toBeInTheDocument();});
it('displays native failures instead of false saved state',async()=>{window.orchestra!.ai!.configure=vi.fn().mockResolvedValue({ok:false,error:{code:'failed',message:'Model access failed'}});render(<DesktopAiSettings/>);await screen.findByText('Offline evidence search is available. No AI key is saved.');await userEvent.click(screen.getByRole('button',{name:'Import key, test and restart'}));expect(await screen.findByRole('alert')).toHaveTextContent('Model access failed');});
it('removes configured access only through native confirmation',async()=>{window.orchestra!.ai!.inspect=vi.fn().mockResolvedValue({ok:true,data:{configured:true,preferences:null}});render(<DesktopAiSettings/>);await userEvent.click(await screen.findByRole('button',{name:'Remove AI access'}));expect(window.orchestra!.ai!.revoke).toHaveBeenCalledOnce();});
