import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,lstat,rm,writeFile,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {connect} from 'node:net';
import {startMcpSocket} from '../src/desktop/mcp-socket.js';
import {localHttp} from '../apps/desktop/src/local-http.js';
import type {HostClient} from '../apps/desktop/src/host-client.js';
import {pairingSetup} from '../apps/desktop/src/mcp-pairing.js';
const directories:string[]=[];const servers:Array<Awaited<ReturnType<typeof startMcpSocket>>>=[];
afterEach(async()=>{vi.unstubAllGlobals();for(const server of servers.splice(0))await server.close();for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});
async function root(){const value=await mkdtemp('/private/tmp/orchestra-mcp-test-');directories.push(value);return value;}
function request(path:string,value:unknown){return new Promise<string>((resolve,reject)=>{const socket=connect(path);let result='';socket.on('connect',()=>socket.write(JSON.stringify(value)+'\n'));socket.on('data',chunk=>result+=chunk);socket.on('end',()=>resolve(result));socket.on('error',reject);});}
describe('native MCP transport boundary',()=>{
 it('allows only the native create and revoke contracts through the desktop allowlist',async()=>{const host={credentials:()=>({port:12345,bearer:'synthetic-bearer',token:'synthetic-installation'})} as unknown as HostClient;const fetch=vi.fn().mockImplementation(async()=>Response.json({data:{}}));vi.stubGlobal('fetch',fetch);for(const path of ['/v1/mcp/tokens','/v1/mcp/tokens/11111111-1111-4111-8111-111111111111/revoke'])expect((await localHttp(new Request('orchestra://app'+path,{method:'POST',body:'{}'}),host,true)).status).toBe(200);expect(fetch).toHaveBeenCalledTimes(2);expect((await localHttp(new Request('orchestra://app/v1/mcp/tokens'),host,true)).status).toBe(403);expect((await localHttp(new Request('orchestra://app/v1/mcp/unapproved',{method:'POST'}),host,true)).status).toBe(403);expect(fetch).toHaveBeenCalledTimes(2);});
 it('binds a private socket and forwards only authenticated MCP requests',async()=>{const directory=await root();const handle=vi.fn().mockResolvedValue({jsonrpc:'2.0',id:1,result:{tools:[]}});servers.push(await startMcpSocket(directory,handle));expect((await lstat(join(directory,'mcp.sock'))).mode&0o777).toBe(0o600);const token='mcp_'+'a'.repeat(43);const result=JSON.parse(await request(join(directory,'mcp.sock'),{token,request:{jsonrpc:'2.0',id:1,method:'tools/list'}}));expect(result.response.result.tools).toEqual([]);expect(handle).toHaveBeenCalledWith('Bearer '+token,expect.objectContaining({method:'tools/list'}));});
 it('rejects unknown commands and credential-shaped payloads before service dispatch',async()=>{const directory=await root(),handle=vi.fn();servers.push(await startMcpSocket(directory,handle));const result=JSON.parse(await request(join(directory,'mcp.sock'),{token:'bad',request:{method:'shell.execute'}}));expect(result.response.error).toBeDefined();expect(handle).not.toHaveBeenCalled();});
 it('never replaces an unrelated regular file at the socket destination',async()=>{const directory=await root();await writeFile(join(directory,'mcp.sock'),'keep');await expect(startMcpSocket(directory,vi.fn())).rejects.toThrow('Unexpected');expect(await readFile(join(directory,'mcp.sock'),'utf8')).toBe('keep');});
 it('keeps model and runtime credentials out of client configuration',()=>{const id='11111111-1111-4111-8111-111111111111';const config=pairingSetup(id,'codex','/Applications/Orchestra App/executable','/private/tmp/profile');expect(config).toContain('--orchestra-mcp='+id);expect(config).not.toMatch(/token|api.?key|authorization/i);expect(JSON.parse(pairingSetup(id,'cursor','/app','/profile')).mcpServers).toBeDefined();expect(JSON.parse(pairingSetup(id,'vscode','/app','/profile')).servers).toBeDefined();});
 it('blocks renderer token administration including encoded paths',async()=>{const credentials=vi.fn();const host={credentials} as unknown as HostClient;for(const path of ['/v1/mcp/tokens','/v1/%6dcp/tokens','/v1/mcp/%74okens']){const response=await localHttp(new Request('orchestra://app'+path,{method:'POST'}),host);expect(response.status).toBe(403);}expect(credentials).not.toHaveBeenCalled();});
});
