import {describe,expect,it,vi} from 'vitest';
import {z} from 'zod';
import {DesktopAiProvider,desktopAiEnvironment,type DesktopAi} from '../src/desktop/ai-provider.js';
import type {createOpenAiClient} from '../src/lib/ai/openai-client.js';
const config:DesktopAi={apiKey:'synthetic-api-key-for-tests-only',preferences:{generationModel:'chosen-model',embeddingModel:'text-embedding-3-small',embeddingDimensions:1536,maxRequestsPerDay:10,maxOutputTokens:256}};
const completed=(text:string)=>({type:'response.completed',response:{status:'completed',output:[{type:'message',status:'completed',content:[{type:'output_text',text}]}]}});
function setup(events:unknown[]=[{type:'response.output_text.delta',delta:'Evidence answer'},completed('Evidence answer')]){
 const checkRequestLimit=vi.fn().mockResolvedValue({allowed:true});
 const create=vi.fn(async(input:{stream?:boolean},_options?:{signal:AbortSignal})=>input.stream?(async function*(){for(const event of events)yield event;})():{status:'completed',output_text:'{"ok":true}'});
 const embed=vi.fn().mockResolvedValue({data:[{embedding:Array(1536).fill(0.1)}]});
 const client={responses:{create},embeddings:{create:embed}} as unknown as ReturnType<typeof createOpenAiClient>;
 return {provider:new DesktopAiProvider(config,{checkRequestLimit},client),checkRequestLimit,create,embed};
}
describe('desktop external AI boundary',()=>{
 it('does not cut off a healthy stream at its inactivity deadline',async()=>{const {provider,create}=setup();create.mockImplementation(async()=> (async function*(){for(let i=0;i<4;i++){await new Promise(resolve=>setTimeout(resolve,10));yield {type:'response.output_text.delta',delta:'word '};}yield completed('word word word word ');})());await expect(provider.streamText({prompt:'test',fallback:()=>'',onDelta:()=>{},timeoutMs:30})).resolves.toBe('word word word word ');});
 it('aligns router, classifier, escalation and client metadata with the selected model',()=>{const env=desktopAiEnvironment(config);expect(env).not.toHaveProperty('SOCRATES_MODEL_ROUTER');for(const key of ['SOCRATES_ROUTER_MODEL','SOCRATES_ESCALATION_MODEL','SOCRATES_CLASSIFIER_MODEL','SOCRATES_SUMMARY_MODEL','SOCRATES_RERANK_MODEL','VSCODE_SOCRATES_MODEL'])expect(env[key as keyof typeof env]).toBe('chosen-model');});
 it('honours the caller deadline for streaming and structured requests',async()=>{for(const structured of [false,true]){const {provider,create}=setup();create.mockImplementation((_input,options)=>new Promise((_resolve,reject)=>options!.signal.addEventListener('abort',()=>reject(new DOMException('Timed out','AbortError')),{once:true})));const request=structured?provider.generateObject({prompt:'test',schema:z.object({ok:z.boolean()}),fallback:()=>({ok:false}),timeoutMs:5}):provider.streamText({prompt:'test',fallback:()=>'',onDelta:()=>{},timeoutMs:5});await expect(request).rejects.toMatchObject({name:'AbortError'});expect(create).toHaveBeenCalledTimes(1);}});
 it('rejects invalid deadlines before sending a request',async()=>{const {provider,create}=setup();await expect(provider.streamText({prompt:'test',fallback:()=>'',onDelta:()=>{},timeoutMs:NaN})).rejects.toMatchObject({code:'invalid_ai_timeout'});expect(create).not.toHaveBeenCalled();});
 it('uses only selected model, output ceiling, no server storage',async()=>{const {provider,create,checkRequestLimit}=setup();const fallback=vi.fn();expect(await provider.generateObject({prompt:'test',schema:z.object({ok:z.boolean()}),fallback,model:'unapproved-expensive-model',maxOutputTokens:5000})).toEqual({ok:true});expect(create.mock.calls[0][0]).toMatchObject({model:'chosen-model',max_output_tokens:256,store:false});expect(checkRequestLimit).toHaveBeenCalledWith({key:'desktop:external-ai',maxRequests:10,windowMs:86400000});expect(fallback).not.toHaveBeenCalled();});
 it('does not transmit when durable request allowance denies',async()=>{const {provider,create,checkRequestLimit}=setup();checkRequestLimit.mockResolvedValue({allowed:false});await expect(provider.streamText({prompt:'question',fallback:()=>'',onDelta:()=>{}})).rejects.toMatchObject({code:'ai_request_budget_exceeded'});expect(create).not.toHaveBeenCalled();});
 it('streams incrementally and requires completed response',async()=>{const {provider}=setup();const delta=vi.fn();expect(await provider.streamText({prompt:'question',fallback:()=>'',onDelta:delta})).toBe('Evidence answer');expect(delta).toHaveBeenCalledWith('Evidence answer');const incomplete=setup([{type:'response.output_text.delta',delta:'partial'}]);await expect(incomplete.provider.streamText({prompt:'question',fallback:()=>'',onDelta:()=>{}})).rejects.toMatchObject({code:'ai_provider_failed'});});
 it('rejects truncated output instead of pretending completion',async()=>{const {provider}=setup([{type:'response.incomplete'}]);await expect(provider.streamText({prompt:'question',fallback:()=>'',onDelta:()=>{}})).rejects.toMatchObject({code:'ai_provider_failed'});});
 it('redacts provider failures and does not invoke fallback',async()=>{const {provider,create}=setup();create.mockRejectedValue(new Error(config.apiKey));const fallback=vi.fn();await expect(provider.generateObject({prompt:'x',schema:z.any(),fallback})).rejects.not.toThrow(config.apiKey);expect(fallback).not.toHaveBeenCalled();});
 it('rejects oversized prompts before budget consumption',async()=>{const {provider,checkRequestLimit}=setup();await expect(provider.embedText('x'.repeat(64001))).rejects.toMatchObject({code:'ai_context_too_large'});expect(checkRequestLimit).not.toHaveBeenCalled();});
 it('honours cancellation before transmission',async()=>{const {provider,create}=setup();await expect(provider.streamText({prompt:'x',signal:AbortSignal.abort(),fallback:()=>'',onDelta:()=>{}})).rejects.toMatchObject({name:'AbortError'});expect(create).not.toHaveBeenCalled();});
 it('revocation prevents future requests',async()=>{const {provider,embed}=setup();provider.revoke();await expect(provider.embedText('x')).rejects.toMatchObject({code:'ai_revoked'});expect(embed).not.toHaveBeenCalled();});
 it('pins embedding identity and rejects invalid vector shape',async()=>{const {provider,embed}=setup();expect((await provider.embedText('x')).length).toBe(1536);expect(embed).toHaveBeenCalledWith({model:'text-embedding-3-small',dimensions:1536,input:'x'},expect.anything());embed.mockResolvedValue({data:[{embedding:[0.1]}]});await expect(provider.embedText('x')).rejects.toMatchObject({code:'ai_provider_failed'});});
});
