import { apiJson } from "./client";

export type DeliveryEvidence = { id: string; label: string; detail: string | null; status: string | null; occurredAt: string | null; openTarget: { targetType: string; targetRef: Record<string, unknown> } | null };
export type DeliveryTraceStep = { key: string; label: string; status: "complete" | "pending" | "blocked" | "not_applicable"; owner: string | null; occurredAt: string | null; detail: string; evidence: DeliveryEvidence[]; remainingGap: string | null };
export type DecisionReceipt = { id: string; proposalId: string; decisionRecordId: string | null; receiptVersion: number; contentHash: string; content: { originalRequest: string; acceptedWording: string; approvedBy: string | null; approvedAt: string | null; affectedScope: string[]; responsibleOwners: string[]; implementationEvidence: DeliveryEvidence[]; testEvidence: DeliveryEvidence[]; deploymentEvidence: DeliveryEvidence[]; knownLimitations: string[]; remainingFollowUp: string[]; issuedAt: string }; issuedAt: string; immutable: true };
export type DecisionDeliveryTrace = { id: string; projectId: string; proposalId: string | null; decisionRecordId: string | null; title: string; status: "review_only" | "awaiting_decision" | "in_delivery" | "blocked" | "delivered"; completedSteps: number; applicableSteps: number; receiptEligible: boolean; receiptBlockers: string[]; receipt: DecisionReceipt | null; steps: DeliveryTraceStep[]; generatedAt: string; limitations: string[] };
export type ContextHealthComponent = { key: string; label: string; state: "healthy" | "attention" | "blocked" | "unknown"; summary: string; detail: string[]; openTarget: { targetType: string; targetRef: Record<string, unknown> } | null };
export type ReleaseTruthItem = { id: string; label: string; detail: string; status: string; occurredAt: string | null; openTarget: { targetType: string; targetRef: Record<string, unknown> } | null };
export type WeeklyBrief = { id: string; weekStart: string; weekEnd: string; sourceFingerprint: string; content: { title: string; weekStart: string; weekEnd: string; whatChanged: BriefItem[]; approved: BriefItem[]; rejected: BriefItem[]; implemented: BriefItem[]; blocked: BriefItem[]; needsDecision: BriefItem[]; possibleDrift: BriefItem[]; missingEvidence: BriefItem[]; limitations: string[] }; generatedAt: string };
export type BriefItem = { id: string; statement: string; sourceLabel: string; occurredAt: string | null; openTarget: { targetType: string; targetRef: Record<string, unknown> } | null };
export type DeliveryOverview = {
  projectId: string;
  contextHealth: { state: "healthy" | "attention" | "blocked" | "unknown"; components: ContextHealthComponent[]; generatedAt: string; limitations: string[] };
  releaseTruth: { readiness: "ready" | "needs_attention" | "blocked" | "unknown"; summary: string; assessedRevision: string | null; assessedRepository: string | null; assessedEnvironment: string | null; assessmentScope: string; acceptedChanges: ReleaseTruthItem[]; implementationEvidence: ReleaseTruthItem[]; unresolvedDecisions: ReleaseTruthItem[]; missingTests: ReleaseTruthItem[]; unsafeAreas: ReleaseTruthItem[]; staleAgentContext: ReleaseTruthItem[]; deploymentEvidence: ReleaseTruthItem[]; blockers: string[]; generatedAt: string; limitations: string[] };
  weeklyBrief: WeeklyBrief | null;
  recentAgentRuns: Array<{ id: string; title: string; status: string; provider: string | null; commitSha: string | null; prUrl: string | null; testStatus: string | null; requiresHumanReview: boolean; review: { scoreLabel: string; recommendation: string; summary: string; needsFollowUp: boolean } | null; updatedAt: string }>;
  generatedAt: string;
  cached: boolean;
};
export type AgentPreflight = { ready: boolean; readinessLabel: "ready" | "needs_decision" | "blocked"; blockers: string[]; currentAcceptedTruth: string[]; relevantEvidence: string[]; technicalConstraints: string[]; knownConflicts: string[]; safeToTouch: string[]; affectedAreas: string[]; requiredTests: string[]; openQuestions: string[]; implementationBoundaries: string[]; contextPack: { id: string; title: string; bodyMarkdown: string; sourceCount: number; evidenceCount: number; warnings: string[]; limitations: string[] }; generatedAt: string; limitations: string[] };

export const getDeliveryOverview = (projectId: string, refresh = false, signal?: AbortSignal) => apiJson<DeliveryOverview>(`/v1/projects/${projectId}/delivery${refresh ? "?refresh=true" : ""}`, { signal });
export const getDecisionDeliveryTrace = (projectId: string, itemId: string, signal?: AbortSignal) => apiJson<DecisionDeliveryTrace>(`/v1/projects/${projectId}/delivery/traces/${encodeURIComponent(itemId)}`, { signal });
export const issueDecisionReceipt = (projectId: string, itemId: string) => apiJson<DecisionReceipt>(`/v1/projects/${projectId}/delivery/receipts/${encodeURIComponent(itemId)}`, { method: "POST", body: "{}" });
export const generateWeeklyBrief = (projectId: string) => apiJson<WeeklyBrief>(`/v1/projects/${projectId}/delivery/weekly-brief`, { method: "POST", body: "{}" });
export const generateAgentPreflight = (projectId: string, input: { taskPrompt: string; proposalId?: string; targetAgent: "codex" | "claude" | "cursor" | "github_agent" | "other"; budgetPreset: "compact" | "normal" | "detailed" }) => apiJson<AgentPreflight>(`/v1/projects/${projectId}/delivery/agent-preflight`, { method: "POST", body: JSON.stringify(input) });
export const generateAgentPostflight = (projectId: string, runId: string) => apiJson<{ run: Record<string, unknown>; review: { scoreLabel: string; recommendation: string; summary: string; findings: Array<{ summary: string; severity: string }> }; acceptedTruthChanged: false; generatedAt: string }>(`/v1/projects/${projectId}/delivery/agent-postflight/${runId}`, { method: "POST", body: "{}" });
