import type { PrismaClient } from "@prisma/client";
import type { Logger } from "pino";
import type { AppEnv } from "../config/env.js";
import type { EmbeddingProvider, GenerationProvider } from "../lib/ai/provider.js";
import type { AiLimiter } from "../lib/ai-ops/ai-limits.js";
import type { TranscriptionProvider } from "../lib/ai/provider.js";
import type { JobDispatcher } from "../lib/jobs/types.js";
import type { TelemetryService } from "../lib/observability/telemetry.js";
import type { StorageDriver } from "../lib/storage/types.js";
import type { AuditService } from "../modules/audit/service.js";
import type { AuthService } from "../modules/auth/service.js";
import type { BrainService } from "../modules/brain/service.js";
import type { ChangeProposalService } from "../modules/changes/service.js";
import type { ProjectDocumentGenerationService } from "../modules/documents/document-generation.service.js";
import type { DocumentService } from "../modules/documents/service.js";
import type { DashboardService } from "../modules/dashboard/service.js";
import type { BetaTimelineService } from "../modules/beta-timeline/beta-timeline.service.js";
import type { LiveDocService } from "../modules/live-doc/service.js";
import type { ProjectService } from "../modules/projects/service.js";
import type { ProjectResponsibilitiesService } from "../modules/projects/responsibilities.service.js";
import type { ProjectContextService } from "../modules/projects/context.service.js";
import type { ProjectDiagramService } from "../modules/diagrams/service.js";
import type { CodingRequirementsService } from "../modules/coding-requirements/service.js";
import type { CommunicationsService } from "../modules/communications/communications.service.js";
import type { SocratesService } from "../modules/socrates/service.js";
import type { SocratesActionService } from "../modules/socrates/actions.service.js";
import type { ClientSharesService } from "../modules/client-view/client-shares.service.js";
import type { ClientViewService } from "../modules/client-view/client-view.service.js";
import type { ProjectOpsService } from "../modules/project-ops/service.js";
import type { RecurringService } from "../modules/project-ops/recurring.service.js";
import type { CalendarConnectionsService } from "../modules/project-ops/calendar-connections.service.js";
import type { GoogleDriveService } from "../modules/google-drive/service.js";
import type { CostEntriesService } from "../modules/project-ops/cost-entries.service.js";
import type { RollupsService } from "../modules/project-ops/rollups.service.js";
import type { AgentContextPackService } from "../modules/agent-context/service.js";
import type { AgentRunMemoryService } from "../modules/agent-context/agent-runs.service.js";
import type { AgentQualityDriftService } from "../modules/agent-context/quality-drift.service.js";
import type { AgentFilesService } from "../modules/agent-files/service.js";
import type { GitHubIntegrationService } from "../modules/github/service.js";
import type { EngineeringEvidenceService } from "../modules/engineering-evidence/service.js";
import type { FdeReadinessIntelligenceService } from "../modules/fde-readiness/service.js";
import type { McpService } from "../modules/mcp/service.js";
import type { EditorConnectorService } from "../modules/editor-connectors/service.js";
import type { SuggestionsService } from "../modules/suggestions/suggestions.service.js";
import type { MeService } from "../modules/me/me.service.js";
import type { IntegrationManagementService } from "../modules/integrations/integrations.service.js";
import type { DeepResearchService } from "../modules/deep-research/service.js";
import type { TruthInboxService } from "../modules/truth-inbox/truth-inbox.service.js";
import type { TruthChangePacketService } from "../modules/truth-inbox/truth-change-packet.service.js";
import type { TruthImpactMapService } from "../modules/truth-inbox/truth-impact-map.service.js";
import type { DeliveryIntelligenceService } from "../modules/delivery/service.js";
import type { SocratesFeedbackService } from "../modules/socrates/feedback.service.js";

export interface AppServices {
  authService: AuthService;
  projectService: ProjectService;
  projectResponsibilitiesService: ProjectResponsibilitiesService;
  projectContextService: ProjectContextService;
  projectDiagramService: ProjectDiagramService;
  codingRequirementsService: CodingRequirementsService;
  documentService: DocumentService;
  documentGenerationService: ProjectDocumentGenerationService;
  brainService: BrainService;
  changeProposalService: ChangeProposalService;
  auditService: AuditService;
  socratesService: SocratesService;
  socratesActionService: SocratesActionService;
  dashboardService: DashboardService;
  betaTimelineService: BetaTimelineService;
  liveDocService: LiveDocService;
  communicationsService: CommunicationsService;
  projectOpsService: ProjectOpsService;
  recurringService: RecurringService;
  calendarConnectionsService: CalendarConnectionsService;
  googleDriveService: GoogleDriveService;
  costEntriesService: CostEntriesService;
  rollupsService: RollupsService;
  clientSharesService: ClientSharesService;
  clientViewService: ClientViewService;
  agentContextPackService: AgentContextPackService;
  agentRunMemoryService: AgentRunMemoryService;
  agentQualityDriftService: AgentQualityDriftService;
  agentFilesService: AgentFilesService;
  githubIntegrationService: GitHubIntegrationService;
  meService: MeService;
  suggestionsService: SuggestionsService;
  truthInboxService: TruthInboxService;
  truthImpactMapService: TruthImpactMapService;
  truthChangePacketService: TruthChangePacketService;
  deliveryIntelligenceService: DeliveryIntelligenceService;
  socratesFeedbackService: SocratesFeedbackService;
  integrationManagementService: IntegrationManagementService;
  engineeringEvidenceService: EngineeringEvidenceService;
  fdeReadinessService: FdeReadinessIntelligenceService;
  mcpService: McpService;
  editorConnectorService: EditorConnectorService;
  deepResearchService: DeepResearchService;
}

export interface AppContext {
  env: AppEnv;
  logger: Logger;
  prisma: PrismaClient;
  storage: StorageDriver;
  generationProvider: GenerationProvider;
  embeddingProvider: EmbeddingProvider;
  transcriptionProvider: TranscriptionProvider;
  jobs: JobDispatcher;
  telemetry: TelemetryService;
  aiLimiter: AiLimiter;
  services: AppServices;
}
